### ISSUE TITLE
[FEATURE]: Multiple enhancement requests

### ISSUE THREAD

**Issue by cyber-sec0** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#1008]
Is your Python program optimized to not go over the rate limits below?
![image](https://github.com/user-attachments/assets/a1a1cf64-3437-4ee5-8d22-fdd92e3fb689)

If not, an enhancement that you could add would be to let users custom set a delay+tokens limit for the AI to use, since each AI model has a different delay+token limits etc.

**Comment by cyber-sec0** [comment]
I didn't use tab spacing before the symbol - anywhere on my work_preferences.yaml file, so this broke the program and it didn't run.

This is a silly issue that's hard to notice... I thought that the program "parser" would be smarter and be able to handle that.
As soon as I added a tab before each - symbol, it worked.

**Comment by cyber-sec0** [comment]
The YT video shows that if I want to erase "achievements" etc, I have to go through the code and erase it in multiple files...

I recommend that the software "parser" should be smart enough and work with/without these file key names automatically, instead of requiring the user to "code".

**Comment by feder-cr** [comment]
@cyber-sec0 do you want work on this?

**Comment by cyber-sec0** [comment]
I would love to work on this project!

But I'll be pretty busy for the next 6 months, so I'm not even coding my personal projects...

At the time, although I could look at the code and answer 2 out of these 3 questions, I would prefer to get the answer, so I can save time.
