### ISSUE TITLE
[DOCS]:Auto_Jobs_Applier_AI-Agent does not apply to jobs anymore , the documentation needs to be updated.

### ISSUE THREAD

**Issue by m7saikat** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#1011]
### Documentation improvement description

After the latest update, @feder-cr  confirmed that this agent would NOT be applying to jobs anymore. This would only be used to generate resume and cover letter.

Given these changes the documentation should be updated.

See #1000 

### Why is this change necessary?

see #1000

**Comment by cyber-sec0** [comment]
See https://github.com/AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent/pull/1010

**Comment by franciscof5** [comment]
that terrible... it was absolutelly great... but it was become very popular and starting getting some bad attetion, hopefully github community stays above the big corporation legal issues, but we all know that it's almost impossible, if they offer like a million dollars for you to remove your project and change it to a dumb project or any other tatics they use we are out

**Comment by cyber-sec0** [comment]
It will work in the future for another platform, maybe...

Sadly, I don't know if any other alternatives similar to this that actually auto applied.

-------- Original Message --------

**Comment by ilyas-it83** [comment]
While working with the codebase yesterday, I noticed that the class names referenced in the code have been updated on the LinkedIn page. As a result, the functionality for retrieving and applying to job listings is currently broken
