### ISSUE TITLE
[DOCS]: .\virtual\Scripts\activate on Windows

### ISSUE THREAD

**Issue by erperejildo** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#1017]
### Documentation improvement description

> PS C:\Users\Dani> .\virtual\Scripts\activate
> .\virtual\Scripts\activate : The term '.\virtual\Scripts\activate' is not recognized as the name of a cmdlet,
> function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
> path is correct and try again.
> At line:1 char:1
> + .\virtual\Scripts\activate
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (.\virtual\Scripts\activate:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException

### Additional context

Where should I run this in Windows 11?

**Comment by JamesTsetsekas** [comment]
try running "python -m venv virtual" first then run ".\virtual\Scripts\activate"
