### ISSUE TITLE
US Sponsorship now or in the future Bug

### ISSUE THREAD

**Issue by abrohit** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#388]
Configured the `plain_test.yaml` as such:

> legal_authorization:
  eu_work_authorization: "No"
  us_work_authorization: "Yes"
  requires_us_visa: "Yes "
  requires_us_sponsorship: "Yes"
  requires_eu_visa: "Yes"
  legally_allowed_to_work_in_eu: "No"
  legally_allowed_to_work_in_us: "Yes"
  requires_eu_sponsorship: "Yes"

Only applying to jobs in the US, but it keeps saying "No" to needs sponsorship now or in the future in the US when it should say "Yes".

**Comment by karta1502545** [comment]
Same problem here.

**Comment by Syerramsetti915** [comment]
The simplest way to solve this issue is to go to the path in your local dir `/LinkedIn_AIHawk_automatic_job_application/answers.json`, find the question you're having trouble with, update it accordingly, save the changes, and then run the script.

**Comment by ParthSoni-CS** [comment]
It's still the same

**Comment by sarob** [comment]
try changing your temperature from 0.4 to 0.7 in llm_manager.py

**Comment by feder-cr** [comment]
@Syerramsetti915 @abrohit @karta1502545 @skaramsi @skaramsi @ParthSoni-CS do you wan work on this?

join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
