### ISSUE TITLE
BUG: generated resumes are identical

### ISSUE THREAD

**Issue by carolinesharpe** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#454]
### Describe the bug

generated resumes are identical

### Steps to reproduce

1. use main
2. run program
3. check generated resumes
4. note that they are all the same as originally uploaded data.

### Expected behavior

custom resumes are generated based on description in job posting

### Actual behavior

resumes are generated with provided quotations in yaml files

### Branch

main

### Python version

3.12

### LLM Used

chat gpt

### Model used

GPT-4o-mini

### Additional context

see attached PDFs for sample of generated resumes. see attached TXT for plaintext.

key area: in experience details, 'responsibility' strings are indentical to phrasing in generated resume

[CV_1727749828.pdf](https://github.com/user-attachments/files/17198652/CV_1727749828.pdf)
[CV_1727749963.pdf](https://github.com/user-attachments/files/17198653/CV_1727749963.pdf)
[CV_1727750085.pdf](https://github.com/user-attachments/files/17198655/CV_1727750085.pdf)
[CV_1727750198.pdf](https://github.com/user-attachments/files/17198656/CV_1727750198.pdf)
[CV_1727750337.pdf](https://github.com/user-attachments/files/17198657/CV_1727750337.pdf)
[CV_1727750478.pdf](https://github.com/user-attachments/files/17198658/CV_1727750478.pdf)
[CV_1727750603.pdf](https://github.com/user-attachments/files/17198659/CV_1727750603.pdf)

[plaintext resume aihawk.txt](https://github.com/user-attachments/files/17198638/plaintext.resume.aihawk.txt)

**Comment by carolinesharpe** [comment]
i tested a few things this week. 
1. changing/adding to skills acquired did not improve customization
2. using more generalized information in responsibilities section did not improve customization
3. achievements section was customized each time, but work experience was not.

**Comment by feder-cr** [comment]
@carolinesharpe can you work on this?

**Comment by feder-cr** [comment]
@carolinesharpe join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
