### ISSUE TITLE
[BUG]: Postings asking for State, ai inputs my ethnicity instead

### ISSUE THREAD

**Issue by burn0ut7** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#472]
### Describe the bug

[BUG]: Postings asking for State, ai inputs my ethnicity instead

### Branch

None

**Comment by cwort40** [comment]
getting this issue too. does it seem to matter where you add the state parameter in this case?

**Comment by burn0ut7** [comment]
> getting this issue too. does it seem to matter where you add the state parameter in this case?
I got this to work. I added this parameter to plain_text_resume.yaml under personal_information. 

Also i didn't look through the code to see if any of this matters, i think it's just logs but just in case i updated it in my answers.json. Also when the bot inputted in the ethnicity i corrected it to the state. 

Now it appears to be working.
