### ISSUE TITLE
[FEATURE]: Website or portfolio site in plain_text_resume.yaml

### ISSUE THREAD

**Issue by Saltiola7** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#483]
### Feature description

when the easy apply form asks for a website, I want my website to be input into it. Right now its inputting something like "I don't have a website" as its not part of the code or config file.

could I just add my website into the yaml file?

### Motivation

more data is better

### Alternatives considered

no

**Comment by feder-cr** [comment]
@Saltiola7 can you work on this?
