### ISSUE TITLE
[BUG]: <Ethnicity is being put down instead of State in applications>

### ISSUE THREAD

**Issue by cwort40** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#484]
### Describe the bug

As I'm watching the application run and fill out Indeed applications, it is putting in the Ethnicity "Hispanic" instead of State which should be "California". 

### Steps to reproduce

Putting "Hispanic" in ethnicity field in `data_folder/plain_text_resume`

### Expected behavior

California

### Actual behavior

Hispanic

### Branch

main

### Python version

3.10

### LLM Used

ChatGPT 

### Model used

4-o mini

**Comment by abintro** [comment]
Same thing is happening here. Same model, LLM and provider.

Using WIndows 11 Powershell to run the bot. There is no field in resume config for "State" field.

**Comment by mcwebdev** [comment]
Why doesn't it look at the answers.json before attempting to us the llm?

**Comment by abintro** [comment]
> @cwort40 can you share how are you running this for indeed. Just thought it only works for LinkedIn Easy Apply.

Some Easy Apply companies ask for a location, which includes States in the US. The state is being filled with ethnicity.

**Comment by abintro** [comment]
@cwort40 Solution is edit resume_schema.yaml and plain_text_resume.yaml and add a field for State to both of these.
