### ISSUE TITLE
[BUG]: Applying to jobs in england despite clearly specifying NYC in the locations!

### ISSUE THREAD

**Issue by naticio** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#496]
### Describe the bug

Applying to jobs in england despite clearly specifying NYC in the locations!

### Steps to reproduce

locations:
  - New York, NY
  
  but bot applied to London

### Expected behavior

apply only to jobs in Locations (new york, ny)

### Actual behavior

applied to London

### Branch

main

### Model used

'gpt-4o-mini'

**Comment by srtandon** [comment]
@naticio i am experiencing something similar.
Was your remote set to true?
Are you running in linux?
Have you found a fix?
