### ISSUE TITLE
[FEATURE]: Refer to answers.json when completing easy apply questions.

### ISSUE THREAD

**Issue by mcwebdev** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#505]
### Feature summary

Refer to answers.json when completing easy apply questions.

### Feature description

When answering additional questions i.e.(How many years of experience with "x"), the script should refer to the answers.json

### Motivation

more explicit control over the answers

**Comment by sloganking** [comment]
I just started playing with this. I see that questions encountered are written to answers.json, but they don't seem to be read from it as the bot writes down the same question with the same default answers it gives every time it encounters the same question. So I keep getting a lot of first name questions saved with the same answer. 

Is any form of reading from answers.json implemented yet? Normally, I would not expect it to save duplicate answers to duplicate questions.

**Comment by sloganking** [comment]
https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/blob/4f639023d3549894aa78a4566ae7a94fb4536a4f/src/aihawk_easy_applier.py#L714-L716

Duplicate instances of the same answer are being saved to `answers.json` because the above if statement does not check if an existing answer already exists. AKA

```python
if not existing_answer
```

I will create an issue for this.

**Comment by sloganking** [comment]
PR #558 which fixes issue #557 , might fix this as well. From what saw in the code. Answers were being retrieved from `answers.json` and used by the bot. But the bot would make duplicate questions and answers in `answers.json`. #558 fixes that and thus may make it so you can finally give `answers.json` the values you want and the bot will use them.

**Comment by sarob** [comment]
seems to be working after manually tweaking common answers. the success rate has gone up by about 20%.

**Comment by MTAleadgen** [comment]
where is answers.json? I don't see it.

**Comment by sarob** [comment]
In the root of the projectSean ***@***.*** On Oct 28, 2024, at 14:18, MTAleadgen ***@***.***> wrote:﻿
where is answers.json? I don't see it.

**Comment by feder-cr** [comment]
@mcwebdev @sloganking @MTAleadgen @MuilaerteJunior can you work on this?
