### ISSUE TITLE
[BUG]: Bot not following answers (specific values) provided in the config file

### ISSUE THREAD

**Issue by swingcake** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#506]
### Describe the bug

It's mentioning random value like "1" & "3" for expected and current CTC. The same for notice period, even when it's clearly specified in the yaml file.

### Expected behavior

Take the value from specified answers in yaml file

### Actual behavior

Entering random values

### Branch

None

### LLM Used

OpenAI

### Model used

gpt-4o-mini

**Comment by sloganking** [comment]
I don't see a pre-designated field to provide questions and answers to those questions in the config.yaml file. Is that even an existing and intended feature right now? @swingcake Can you provide the portion of your config file that you are attempting to put answers for questions in?
