### ISSUE TITLE
Feature Request: Toggle to disable list of skills after every work experience

### ISSUE THREAD

**Issue by Charleezy** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#510]
### Feature summary

After every work experience there's a list of experience including about 20 different skills

### Feature description

After every work experience there's a list of experience including about 20 different skills, I'd like for this to be removable

### Motivation

I think it makes the resume look automatically generated and is verbose

### Alternatives considered

If there were a way to submit the resume without modifications through an AI this would also work
I'd be willing to make the change if I could get some help on how to
![Environment on Resume](https://github.com/user-attachments/assets/cb34f25d-9c91-4f4d-b0f4-d005fec84cd7)

I can understand that including this helps with the resume scanners employers use, but there must be a better way? Maybe just to include it once?

**Comment by feder-cr** [comment]
@Charleezy can you work on this?
