### ISSUE TITLE
[BUG]: from lib-resume_builder_AIHawk import Resume,StyleManager, FacadeManager,Resume Generator ModuleNotFoundError: No module named 'lib_resume_builder_AiHawk'

### ISSUE THREAD

**Issue by Fredo23** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#583]
### Describe the bug

Whenever I try to run the bot I get this error message from lib-resume_builder_AIHawk import Resume,StyleManager, FacadeManager,Resume Generator ModuleNotFoundError: No module named 'lib_resume_builder_AiHawk'

### Branch

None

**Comment by yamseats** [comment]
same

**Comment by Fredo23** [comment]
did you ever fix it?

**Comment by Avaneeshakrishna** [comment]
yes, getting same error

**Comment by amishra15** [comment]
Any fix?

**Comment by anwarrior** [comment]
I possibly found a solution for this, there is another repo named "lib_resume_builder_AIHawk", try cloning it.

**Comment by CharlieSalinas** [comment]
> I possibly found a solution for this, there is another repo named "lib_resume_builder_AIHawk", try cloning it.

Where is thiis repo?

**Comment by jmrsmace9831** [comment]
Did anybody ever find a fix for this "No module named 'lib_resume_builder_AiHawk' " error?
