### ISSUE TITLE
[FEATURE]: Add Azure OpenAI

### ISSUE THREAD

**Issue by Viper911** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#616]
### Feature summary

Add Azure OpenAI

### Feature description

Can you add LLM to use Azure OpenAI?

### Motivation

I get free credits with MSDN subscription

**Comment by Viper911** [comment]
I thought it might be as easy as updating the llm_manager.  I have a different program that uses this connection, but it uses openai library rather than langchain sp not sure if this how I would update.

class OpenAIModel(AIModel):
    def __init__(self, api_key: str, llm_model: str):
        ##from langchain_openai import ChatOpenAI
        ##--self.model = ChatOpenAI(model_name=llm_model, openai_api_key=api_key,
        ##                        temperature=0.4)

        from langchain_openai import AzureChatOpenAI

        self.model = AzureChatOpenAI(
            azure_endpoint = ENDPOINT,
            azure_deployment = DEPLOYMENT,
            api_version = API_VERSION,
            api_key = AZURE_API_KEY,  
            temperature=0.4
        )

    def invoke(self, prompt: str) -> BaseMessage:
        logger.debug("Invoking OpenAI API")
        response = self.model.invoke(prompt)
        return response

**Comment by Viper911** [comment]
Got a little closure.  Seems I have to use langchain.chat_models

        from langchain.chat_models import AzureChatOpenAI

        self.model = AzureChatOpenAI(
            deployment_name=DEPLOYMENT,
            openai_api_base=ENDPOINT,
            openai_api_version=API_VERSION,
            openai_api_key=AZURE_API_KEY
        )

Now I get:
2024-10-26 12:39:30.876 | ERROR    | src.llm.llm_manager:parse_llmresult:391 - Unexpected error while parsing LLM result: 'NoneType' object has no attribute 'get'
2024-10-26 12:39:30.877 | ERROR    | src.llm.llm_manager:__call__:332 - Unexpected error occurred: 'NoneType' object has no attribute 'get'
2024-10-26 12:39:30.877 | INFO     | src.llm.llm_manager:__call__:333 - Waiting for 30 seconds before retrying due to an unexpected error.

**Comment by Viper911** [comment]
Yea, I have been able to get connection now.  There is just a bunch of places in code that need to be updated.  For example the token stats dont work with Azure and the resume builder has connection strings in it that seem like they need to be updated.  In any case, I haven;t had time to work through them all so it still doesn't work, but am slowly trying.

________________________________

**Comment by zycarlc** [comment]
I made support on this feature #847

**Comment by 49Simon** [comment]
@feder-cr I would suggest to keep this open until the linked PR is merged.

**Comment by nkshschdv** [comment]
I think , PR is not merged why this is closed ?
