### ISSUE TITLE
[BUG]: from lib_resume_builder_AIHawk import Resume, FacadeManager, ResumeGenerator, StyleManager

### ISSUE THREAD

**Issue by amishra15** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#647]
### Describe the bug

I did everything right but still getting this.

### Branch

None

**Comment by anwarrior** [comment]
Same

**Comment by anwarrior** [comment]
I possibly found a solution for this, there is another repo named "lib_resume_builder_AIHawk", try cloning it.

**Comment by amishra15** [comment]
I already did that but I'm still seeing the same error

**Comment by anwarrior** [comment]
I was able to resolve the issue, above mentioned solution worked for me.
