### ISSUE TITLE
[BUG]: TypeError and problem in module  with class FileManager

### ISSUE THREAD

**Issue by okulardrom** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#657]
### Describe the bug

While trying to run the file main.py the process is returning the following error :  Traceback (most recent call last):   File "C:\Users\okula\Auto_Jobs_Applier_AIHawk\main.py", line 122, in <module>     class FileManager:   File "C:\Users\okula\Auto_Jobs_Applier_AIHawk\main.py", line 139, in FileManager     def file_paths_to_dict(resume_file: Path | None, plain_text_resume_file: Path) -> dict: TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### Steps to reproduce

while inside the virtual environment in cmd in windows:
1: i write python main.py
2: I get this error message:While trying to run the file main.py the process is returning the following error :  Traceback (most recent call last):
  File "C:\Users\okula\Auto_Jobs_Applier_AIHawk\main.py", line 122, in <module>
    class FileManager:
  File "C:\Users\okula\Auto_Jobs_Applier_AIHawk\main.py", line 139, in FileManager
    def file_paths_to_dict(resume_file: Path | None, plain_text_resume_file: Path) -> dict:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### Expected behavior

Run the bot

### Actual behavior

Error

### Branch

main

### Python version

Python 3.9.13

### LLM Used

OpenAI

**Comment by btgendler2005** [comment]
On Line 139, remove None and it will run fine.

**Comment by cjbbb** [comment]
@okulardrom Could you please try to run the new Main branch. Fetch the new coding and try? If anything wrong, let me konw!

**Comment by wonx** [comment]
Hi, I'm experiencing the same issue. I cloned the latest version fo the repo today but the error is still there:

```
Traceback (most recent call last):
  File "/home/user/Auto_Jobs_Applier_AIHawk/main.py", line 129, in <module>
    class FileManager:
  File "/home/user/Auto_Jobs_Applier_AIHawk/main.py", line 146, in FileManager
    def file_paths_to_dict(resume_file: Path | None, plain_text_resume_file: Path) -> dict:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```
