### ISSUE TITLE
[FEATURE]: Add Company Name to Cover Letter Generation Template

### ISSUE THREAD

**Issue by FrancescoVassalli** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#714]
### Feature summary

Cover Letter Company Name

### Feature description

Sometimes the cover letter generation does not make a cover letter with the company name or the company name is wrong. I will add a company name to the cover letter generation template

### Motivation

To get the correct company name when applying

### Alternatives considered

I don't know but I am open to ideas

**Comment by surapuramakhil** [comment]
@FrancescoVassalli kindly keep this open until release happens. do join discord for release co-ordination

**Comment by feder-cr** [comment]
@FrancescoVassalli good idea
