### ISSUE TITLE
[FEATURE]: Make Cover Letter file name not use UNIX time

### ISSUE THREAD

**Issue by FrancescoVassalli** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#717]
### Feature summary

Cover Letter File Name with Job 

### Feature description

Instead of having the the cover letter file name generated with the unix time, I propose making the job name and then just appending `(1)` if there are conflicts. Employers can potentially see this and it looks like a bot. 

### Motivation

Hide that this is a bot 

### Alternatives considered

I think there are a lot of possible solutions to this but that the current one should be changed

**Comment by surapuramakhil** [comment]
I feel correct name should be <cadidate_name>_coverletter.pdf for submission. for tacking (internal thing it can be job_tilte/id_converletter.pdf.

**Comment by feder-cr** [comment]
@surapuramakhil @FrancescoVassalli any updates?

**Comment by FrancescoVassalli** [comment]
> @surapuramakhil @FrancescoVassalli any updates?

I'll make the changes requested in the PR tomorrow or the next day
