### ISSUE TITLE
[BUG]: locations not working properly

### ISSUE THREAD

**Issue by erperejildo** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#750]
### Steps to reproduce

I have this:
```
locations:
  - Germany
  - UK
  - US
```

But it applies for offers in Spain

### Branch

None

### Model used

Gemini

**Comment by surapuramakhil** [comment]
@erperejildo can you add browser's screenshot

**Comment by erperejildo** [comment]
> @erperejildo can you add browser's screenshot

It'd show just an offer from a Spanish company. Is there anything in particular you want to see/check?

**Comment by feder-cr** [comment]
@erperejildo can you work on this?

**Comment by erperejildo** [comment]
> @erperejildo can you work on this?

On what sorry?

**Comment by erperejildo** [comment]
> @erperejildo on this bug

I don't know how to fix it, but let me know if you need a hand to test it

**Comment by queukat** [comment]
@erperejildo The locations field needs to be specified exactly as they appear on the job site. For example:

yaml
Copy code
locations:
  - European Economic Area
  - United Kingdom
Using specific regional names like this ensures the program only applies to relevant locations. Listing locations by country alone (e.g., “Germany,” “UK,” “US”) may lead to unexpected results, like applying for jobs in Spain or even further afield, such as Malaysia.

@feder-cr This issue can be closed now.

**Comment by erperejildo** [comment]
> @erperejildo The locations field needs to be specified exactly as they appear on the job site. For example:
> 
> 
> ```yaml
> locations:
>   - European Economic Area
>   - United Kingdom
> ```
> Using specific regional names like this ensures the program only applies to relevant locations. Listing locations by country alone (e.g., “Germany,” “UK,” “US”) may lead to unexpected results, like applying for jobs in Spain or even further afield, such as Malaysia.
> 
> @feder-cr This issue can be closed now.

Thanks for the info.

Also, how can I target Europe but block some if its countries?

**Comment by surapuramakhil** [comment]
> @erperejildo The locations field needs to be specified exactly as they appear on the job site. For example:
> 
> ```yaml
> locations:
>   - European Economic Area
>   - United Kingdom
> ```
> 
> Using specific regional names like this ensures the program only applies to relevant locations. Listing locations by country alone (e.g., “Germany,” “UK,” “US”) may lead to unexpected results, like applying for jobs in Spain or even further afield, such as Malaysia.
> 
> @feder-cr This issue can be closed now.

</br>

@queukat can you this information in ReadMe

**Comment by erperejildo** [comment]
> 
> > @erperejildo The locations field needs to be specified exactly as they appear on the job site. For example:
> > 
> > ```yaml
> > locations:
> >   - European Economic Area
> >   - United Kingdom
> > ```
> > 
> > Using specific regional names like this ensures the program only applies to relevant locations. Listing locations by country alone (e.g., “Germany,” “UK,” “US”) may lead to unexpected results, like applying for jobs in Spain or even further afield, such as Malaysia.
> > 
> > @feder-cr This issue can be closed now.
> 
> </br>
> 
> @queukat can you this information in ReadMe

Fair enough.

In my case, I want to apply to any country in Europe but Spain. Does it mean I would need to add all the countries one by one if I only want to exclude one?

**Comment by queukat** [comment]
> > > @erperejildo The locations field needs to be specified exactly as they appear on the job site. For example:
> > > ```yaml
> > > locations:
> > >   - European Economic Area
> > >   - United Kingdom
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Using specific regional names like this ensures the program only applies to relevant locations. Listing locations by country alone (e.g., “Germany,” “UK,” “US”) may lead to unexpected results, like applying for jobs in Spain or even further afield, such as Malaysia.
> > > @feder-cr This issue can be closed now.
> > 
> > 
> > 
> > @queukat can you this information in ReadMe
> 
> Fair enough.
> 
> In my case, I want to apply to any country in Europe but Spain. Does it mean I would need to add all the countries one by one if I only want to exclude one?

well, yes. or you can use locations, like: European Economic Area ext
