### ISSUE TITLE
[BUG]: Even after setting the requuires sponsorship to YES, the bot automatically selects no radio button

### ISSUE THREAD

**Issue by anirudha-bs** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#788]
### Describe the bug

Even after setting requires sponsorship to YES and even after giving an example in strings to make the bot answer YES, it still selects NO as the answer.

### Branch

None

**Comment by queukat** [comment]
@anirudha-bs Could you provide more details? The configuration includes parameters for various countries regarding work authorization, so when a country is explicitly mentioned in the question, the program should respond correctly. However, if the question in the application is more general (e.g., “Do you have authorization?” without specifying a country), the program may default to answering “Yes.”

There can also be nuances depending on the model being used, which might affect response behavior.

Additionally, if needed, you can always adjust responses in the answers.json file to achieve the desired outcome. Let us know if that helps or if you can provide more context.
