### ISSUE TITLE
It is recommended to support Chinese mode.

### ISSUE THREAD

**Issue by GaoYuan522** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#794]
It is recommended to support Chinese mode.In this way, you can send a Chinese resume and rely on the language preference of the Chinese-American boss.

**Comment by queukat** [comment]
@GaoYuan522 Could you clarify what you mean? The prompt for the model is designed without specific language requirements for the resume, so it should ideally support generating resumes in Chinese already. If it doesn’t, that would be a prompt-related bug, and examples would be helpful for debugging.

If you’re referring to translating configuration elements into Chinese, that would require someone proficient in both Chinese and programming to ensure accuracy. Let us know which aspect you’re focusing on.

**Comment by GaoYuan522** [comment]
> @GaoYuan522 Could you clarify what you mean? The prompt for the model is designed without specific language requirements for the resume, so it should ideally support generating resumes in Chinese already. If it doesn’t, that would be a prompt-related bug, and examples would be helpful for debugging.
> 
> If you’re referring to translating configuration elements into Chinese, that would require someone proficient in both Chinese and programming to ensure accuracy. Let us know which aspect you’re focusing on.

What I want to express is the latter-to translate the profile into Chinese. I suggest that your group recruit some Chinese people, such as those whose names are Hanyu Pinyin, who are generally proficient in Chinese.
