### ISSUE TITLE
[BUG]: <ai_hawk.job_manager:start_applying:160 - Error during job application: 'NoneType' object has no attribute 'strip'>

### ISSUE THREAD

**Issue by DavidTang1012** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#807]
### Describe the bug

It scrolls but gives above error and didn't apply

### Expected behavior

Successfully applied

### Branch

None

**Comment by surapuramakhil** [comment]
@DavidTang1012 add stacktraces and sufficient log information so that contributors can work on it.
