### ISSUE TITLE
[BUG]: Adding jobs to success.json but not actually applying

### ISSUE THREAD

**Issue by irehsrg** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#852]
### Describe the bug

Bot is running fine and adding jobs to success.json but not actually applying

### Steps to reproduce

python main.py --resume D:\GitHub\Auto_Jobs_Applier_AIHawk\data_folder\Resume.pdf

Output in PowerShell:
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=152, microseconds=399179), 'exception': None, 'extra': {}, 'file': (name='llm_manager.py', path='D:\\GitHub\\Auto_Jobs_Applier_AIHawk\\src\\ai_hawk\\llm\\llm_manager.py'), 'function': 'invoke', 'level': (name='DEBUG', no=10, icon='🐞'), 'line': 40, 'message': 'Invoking OpenAI API', 'module': 'llm_manager', 'name': 'ai_hawk.llm.llm_manager', 'process': (id=16260, name='MainProcess'), 'thread': (id=2852, name='MainThread'), 'time': datetime(2024, 11, 13, 18, 23, 52, 391365, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=64800), 'Central Standard Time'))}
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\loguru\_handler.py", line 206, in emit
    self._sink.write(str_record)
  File "C:\Python312\Lib\site-packages\loguru\_file_sink.py", line 204, in write
    self._terminate_file(is_rotating=True)
  File "C:\Python312\Lib\site-packages\loguru\_file_sink.py", line 276, in _terminate_file
    os.rename(old_path, renamed_path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\\GitHub\\Auto_Jobs_Applier_AIHawk\\log\\app.log' -> 'D:\\GitHub\\Auto_Jobs_Applier_AIHawk\\log\\app.2024-11-06_16-31-07_172728.log'
--- End of logging error ---
2024-11-13 18:23:52.391 | DEBUG    | ai_hawk.llm.llm_manager:invoke:40 - Invoking OpenAI API

### Expected behavior

run correctly

### Actual behavior

doesn't actually apply for jobs

### Branch

main

### Python version

3.13.0

### LLM Used

gpt

### Model used

4o-mini

**Comment by irehsrg** [comment]
[failed.json](https://github.com/user-attachments/files/17759973/failed.json)
[skipped.json](https://github.com/user-attachments/files/17759974/skipped.json)
[success.json](https://github.com/user-attachments/files/17759975/success.json)

**Comment by surapuramakhil** [comment]
@irehsrg this was fixed in release. @cjbbb fixed it.

feel free to reopen if you are still facing it.
