### ISSUE TITLE
[FEATURE]: Add a config for sponsorship

### ISSUE THREAD

**Issue by Shuo-Wang-UCBerkeley** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#864]
### Feature summary

Now the application select that I do not need sponsorship. But I actually needed it. Could we add this feature?

### Feature description

Now the application select that I do not need sponsorship. But I actually needed it. Could we add this feature?

### Motivation

I need sponsorship

**Comment by 49Simon** [comment]
This feature is already supported. In your `plain_text_resume.yaml` file in the `legal_authorization` section, you can specify whether you need one or not.

**Comment by Shuo-Wang-UCBerkeley** [comment]
Hi Team,

Thank you for your reply. I do specify that I need sponsorship, but it selected “no” when applying for the job. 

This is why I ask. I said I need sponsorship, but does not need visa, should I fill “Yes” for all of them?

  us_work_authorization: "Yes"
  requires_us_visa: "No"
  requires_us_sponsorship: "Yes"

Thank you.

**Comment by 49Simon** [comment]
In that case it should have worked properly and selected "Yes". 

Here's what you can do:
1.  Previous answers are saved in `answer.json` file in the root directory. Go through that and check if the requires sponsorship was previous answered as No. If so, change it to yes. There might be different variations how this is asked, so there might be similar duplicates, go through each of them and change them to yes.
2.  There's a new release out today, pull the latest changes and then try again.

**Comment by Shuo-Wang-UCBerkeley** [comment]
Got it, thank you. 

By the way, do you see another question regarding to the driver license?
Now the application selected “no”, but I have driver license, if I simple change it to “yes” in the answer.json, so it will select “yes” in next application? But what if the website ask for my driver license No., how we can let the job website know it?

Thank you.
Shuo Wang

**Comment by 49Simon** [comment]
Currently, thats not implemented. It does not have applicant's driver license info.

**Comment by Shuo-Wang-UCBerkeley** [comment]
Got it, thank you.
Do you know when will the new release happen? I did not see any update today. 


￼

**Comment by 49Simon** [comment]
I'm not sure tbh

**Comment by Shuo-Wang-UCBerkeley** [comment]
Thank you for your reply. I will keep refreshing.

By the way, does this only apply to the “Easy Apply” position on LinkedIn?

Thank you.
Have a good weekend.

**Comment by Shuo-Wang-UCBerkeley** [comment]
Hi,

When I run the code, the following snapshot shows up, it sleep and then exit the loop, and search the new job, but keep shows "no more jobs found on this page.” even if there are many jobs shows on the LinkedIn. Do you know what happened?

￼

Thank you.
Shuo Wang

**Comment by Shuo-Wang-UCBerkeley** [comment]
Hi,

When I run the code, the following snapshot shows up, it sleep and then exit the loop, and search the new job, but keep shows "no more jobs found on this page.” even if there are many jobs shows on the LinkedIn. Do you know what happened?

￼

Thank you.
Shuo Wang
