### ISSUE TITLE
[BUG]: Bot is not applying to jobs

### ISSUE THREAD

**Issue by ArtistYay** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#876]
### Describe the bug

Not sure if this is a bug or my experience is trash but the bot is not applying to any roles. All I'm getting is failed and I'm not sure I'm the only one.

### Steps to reproduce

Honestly, I'm just running the bot for a certain amount of time and getting this every time. There have been no successful applications.

![image](https://github.com/user-attachments/assets/4d1511d5-bd56-47f4-9709-742b385aeea8)

### Expected behavior

Apply to the role regardless.

### Actual behavior

Not applying.

### Branch

None

### Python version

3.10.12

### LLM Used

Gemini

### Model used

gemini-1.5-flash-002

**Comment by 49Simon** [comment]
This issue has been raised in #868. And it should be fixed with PR #869

**Comment by ArtistYay** [comment]
@49Simon looks like the commit is having errors 
![image](https://github.com/user-attachments/assets/47f44a07-e6aa-4531-bc46-4eb749e0d11b)

**Comment by ArtistYay** [comment]
@49Simon The hotfix branch

**Comment by 49Simon** [comment]
@ArtistYay The new commit added to address this issue does not touch any imports and this new error you're facing is not related to that. 

Just to double check, I cloned this repo in a new folder, installed dependencies, checked out to the hotfix branch and it is running as expected without any issues. Can you try pulling the latest code and try again.

**Comment by 49Simon** [comment]
Can you provide more information? The branch you are in, and the error logs

**Comment by 49Simon** [comment]
@ArtistYay Okay, that's another error not related to this issue. I've raised another PR #884 to fix that. It should be merged to hotfix soon. Cc: @surapuramakhil 

For now, you can comment out the import line `from turtle import color` in the `job_manager.py` file.
