### ISSUE TITLE
[BUG]:  ERROR    | __main__:main:226 - Runtime error: Error running the bot: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by earr0103** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#878]
### Describe the bug

I honestly have no idea

### Branch

None

**Comment by earr0103** [comment]
![image](https://github.com/user-attachments/assets/fa7a82ac-565b-4818-9c80-c874eee711b6)

**Comment by earr0103** [comment]
wether i use the --resume option or not after i execute main.py runs fine till it opens chrome then it just closes itself and then the error appears.

**Comment by 49Simon** [comment]
In your `data_folder/work_preferences.yaml` file, can you tell me the entries you have in the `_blacklist` sections at the bottom (for 3 of them). A screenshot will be fine.
