### ISSUE TITLE
[FEATURE]: Job Ranking and Prioritized Applications

### ISSUE THREAD

**Issue by moudimash99** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#937]
### Feature summary

Add a feature to save all job listings, rank them based on multiple factors (e.g., number of applicants, research score, suitability score, time posted), and apply only to the top-ranked jobs.

### Feature description

his feature would enhance the bot by introducing a ranking system for job listings. Instead of applying to jobs as they are found, the bot would first collect all matching listings, evaluate them against user-defined criteria (e.g., number of applicants, research score, suitability score, time since posting), and rank them. The bot would then apply to jobs starting from the highest-ranked ones until user-defined limits (e.g., max applications per run) are reached.

### Motivation

 increasing success rates

**Comment by feder-cr** [comment]
@moudimash99 good idea, do you want work on this!

**Comment by moudimash99** [comment]
@feder-cr yeah I'd love to work on it, if someone wants to join I'd be more than happy though.

**Comment by surapuramakhil** [comment]
@moudimash99 as it's a longer task, I have added in planned.

I would suggest starting with "feature specs", specifying the scope (you can wiki and add link here). then plan & design - creating subtasks which can be done independently
