### ISSUE TITLE
[BUG]: Classnames changes causing no jobs to be found

### ISSUE THREAD

**Issue by kosamkarmansi** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#950]
### Describe the bug

Unable to locate element - "scaffold-layout__list-container"

### Steps to reproduce

<img width="1062" alt="image" src="https://github.com/user-attachments/assets/9b92ae60-533d-41a9-bd23-c00e82304bec">
<img width="1042" alt="image" src="https://github.com/user-attachments/assets/e2229b61-d2a4-4de4-ab12-39f9095351aa">

### Expected behavior

Should select a job

### Actual behavior

Isnt able to select a job

### Branch

main

### Branch name

main

### Python version

3.10.10

### LLM Used

chatgpt

### Additional context

similar to issue 919 - https://github.com/AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent/issues/919

**Comment by ShawWangWX** [comment]
Does anyone get a clue what the new class lable refers to?
<img width="1912" alt="Snipaste_2024-11-26_18-45-14" src="https://github.com/user-attachments/assets/f1709917-9dc1-42cf-aefa-38f97e268604">

**Comment by joelfuller2016** [comment]
my opinion is use AI to pass the entire page and have the output into a useable data source. then have each job pass back into AI then it will provide the button to push. Easy peazy done. Ive used C# to build structured outputs. its all json.

https://platform.openai.com/docs/guides/structured-outputs
