### ISSUE TITLE
[QUESTION]: LinkedIn has completly different layout

### ISSUE THREAD

**Issue by PetrShchukin** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#958]
I'm noticing that almost every second class on my LinkedIn page differs from what's expected. Check out the attached picture: even the formatting for Company_Name - Location is inconsistent. For me (based in Europe), these are displayed separately but separated by a dot (·).  Additionally, some CSS classes seem to be either missing or renamed. For example, I see` job-card-list__footer-wrapper` in the source, but in LinkedIn renders ` job-card-list__footer-wrapper-v2` class. Am I missing something? I tried VPN and connect to the US didn't help. Maybe profile location settings could help, but I am not sure. (And profile is not premium)

![image](https://github.com/user-attachments/assets/70cbb94b-c0a6-4ddb-8e68-335b33f559aa)

**Comment by cjbbb** [comment]
yeah, LinkedIn updated their front-end, we need to modify it and push to hotfix branch.

**Comment by PetrShchukin** [comment]
@cjbbb I am not sure where the best place to report this is. While I am still testing, I managed to get it working by making these changes (Note: tested only with job collection using the command `python main.py --collect`):

![image](https://github.com/user-attachments/assets/fbf3de88-3f23-47a5-babe-de6e8ca83da5)
![image](https://github.com/user-attachments/assets/3cfd973b-cd62-4c0c-b61a-48aa11fe4bc5)
![image](https://github.com/user-attachments/assets/99599af0-df02-41bd-948d-308164bd73ba)

**Comment by cjbbb** [comment]
@PetrShchukin https://github.com/AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent/pull/961
I am working on it. If you have interests, you can try this version (may have some bugs, and you can report by comments to help us fix it); Thanks!
