### ISSUE TITLE
[BUG]: NO MORE JOBS FOUND ON THIS PAGE

### ISSUE THREAD

**Issue by ShabrezNoorani** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#963]
### Describe the bug

I keep getting message >> 2024-11-28 15:22:19.019 | DEBUG    | ai_hawk.job_manager:start_applying:162 - No more jobs found on this page. Exiting loop. Sleeping for 54.75855803489685 seconds. Press 'y' to skip waiting. Timeout 60 seconds : 

### Expected behavior

It goes to the page on linkedin and searches the perfect JOB but on terminal it says no JOBS found refreshing in xx seconds

### Branch

main

### Python version

Python 3.12.7

### LLM Used

Ollama

### Model used

Ollama

### Additional context

Hi Team,

Firstly, thank you for this fantastic tool—it’s been working great overall! However, I’ve encountered a small issue that I wanted to bring to your attention. Everything works fine—it navigates to LinkedIn and searches for the job title perfectly. But instead of applying, the terminal shows the following message:

2024-11-28 15:25:20.193 | DEBUG | ai_hawk.job_manager:start_applying:224 - Sleeping for 53.67443776130676 seconds as user chose not to skip.

I’m not a developer, so I might be missing something, but it seems like the script isn’t detecting the "Easy Apply" button or is stuck in some way. Any guidance on how I can fix or troubleshoot this would be greatly appreciated.

Thank you again for your hard work!

**Comment by TaaroBravo** [comment]
Same here!
