### ISSUE TITLE
[FEATURE]: add undetected - chrome driver

### ISSUE THREAD

**Issue by surapuramakhil** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#967]
### Feature summary

adding undetected - chrome driver

### Feature description

https://github.com/ultrafunkamsterdam/undetected-chromedriver

**Comment by feder-cr** [comment]
@cjbbb

**Comment by surapuramakhil** [comment]
@feder-cr I am working on it, I will be raising PR for this & code refactroring.
