### ISSUE TITLE
[BUG]: won't render page after login: prints out "undetected chromedriver 1337!" in browser console

### ISSUE THREAD

**Issue by Axedyson** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#995]
### Describe the bug

won't render page after login: prints out "undetected chromedriver 1337!" in browser console

### Steps to reproduce

Clear browser cookies/state and login again using the job applier tool.

### Expected behavior

Would render page

### Actual behavior

the linked loading screen is just there forever
<img width="726" alt="image" src="https://github.com/user-attachments/assets/47546f39-ab05-4102-91e0-e5950363c154">

### Branch

None

### Branch name

main

### Python version

3.12.7

### LLM Used

OpenAI's ChatGPT

### Model used

gtp-4o

### Additional context

chrome version: 131.0.6778.108
chromedriver version: 131.0.6778.87

**Comment by slat83** [comment]
Have the same problem

**Comment by BlackHoleExelion** [comment]
Same prob. Obviously something wrong with webdriver_manager or selenium.

**Comment by BlackHoleExelion** [comment]
![图像 001](https://github.com/user-attachments/assets/c3454e89-cd2a-47ee-bfc6-bd55d5f5de0f)
It works again when you comment out `options.add_argument`.

But my prob is that it is not applying for any jobs but showing this:
`2024-12-04 09:35:26.927 | WARNING  | src.job_portals.linkedIn.jobs_page:get_jobs_from_page:155 - No job results found on the page.
 expection: Traceback (most recent call last):
  File "c:\Users\Administrator\Desktop\code\github_aihawk\src\job_portals\linkedIn\jobs_page.py", line 128, in get_jobs_from_page
    jobs_container = self.driver.find_element(By.XPATH, jobs_xpath_query)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\code\github_aihawk\virtual\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 770, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\code\github_aihawk\virtual\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\Desktop\code\github_aihawk\virtual\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//ul[contains(@class, 'scaffold-layout__list-container')]"}
  (Session info: chrome=131.0.6778.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
        GetHandleVerifier [0x007B3433+25059]
        (No symbol) [0x0073CE34]
        (No symbol) [0x0061BEC3]
        (No symbol) [0x0065FD86]
        (No symbol) [0x0065FFCB]
        (No symbol) [0x0069D952]
        (No symbol) [0x00681F44]
        (No symbol) [0x0069B51E]
        (No symbol) [0x00681C96]
        (No symbol) [0x00653FAC]
        (No symbol) [0x00654F3D]
        GetHandleVerifier [0x00AA5593+3113795]
        GetHandleVerifier [0x00ABA25A+3198986]
        GetHandleVerifier [0x00AB2A32+3168226]
        GetHandleVerifier [0x008532A0+680016]
        (No symbol) [0x0074577D]
        (No symbol) [0x00742A28]
        (No symbol) [0x00742BC5]
        (No symbol) [0x00735820]
        BaseThreadInitThunk [0x76A07D59+25]
        RtlInitializeExceptionChain [0x77E6B79B+107]
        RtlClearBits [0x77E6B71F+191]`

**Comment by jayceftg** [comment]
2024-12-04 22:36:23.326 | WARNING  | src.job_portals.linkedIn.jobs_page:get_jobs_from_page:155 - No job results found on the page.
 expection: Traceback (most recent call last):
  File "C:\Users\VG\Desktop\automation\aihawk\new\Auto_Jobs_Applier_AIHawk\src\job_portals\linkedIn\jobs_page.py", line 128, in get_jobs_from_page
    jobs_container = self.driver.find_element(By.XPATH, jobs_xpath_query)
  File "C:\Program Files\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 831, in find_element      
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Program Files\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response 
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//ul[contains(@class, 'scaffold-layout__list-container')]"}
  (Session info: chrome=131.0.6778.86)
Stacktrace:
        GetHandleVerifier [0x00533433+25059]
        (No symbol) [0x004BCE34]
        (No symbol) [0x0039BEC3]
        (No symbol) [0x003DFD86]
        (No symbol) [0x003DFFCB]
        (No symbol) [0x0041D952]
        (No symbol) [0x00401F44]
        (No symbol) [0x0041B51E]
        (No symbol) [0x00401C96]
        (No symbol) [0x003D3FAC]
        (No symbol) [0x003D4F3D]
        GetHandleVerifier [0x00825593+3113795]
        GetHandleVerifier [0x0083A25A+3198986]
        GetHandleVerifier [0x00832A32+3168226]
        GetHandleVerifier [0x005D32A0+680016]
        (No symbol) [0x004C577D]
        (No symbol) [0x004C2A28]
        (No symbol) [0x004C2BC5]
        (No symbol) [0x004B5820]
        BaseThreadInitThunk [0x76577BA9+25]
        RtlInitializeExceptionChain [0x770FBB3B+107]
        RtlClearBits [0x770FBABF+191]
        
        
same, webdriver problem again? it sucks guts.

**Comment by dlin2028** [comment]
Fixed in #993
